FROM openjdk
ADD productos.jar servicios/productos.jar
ENV hostconfig=192.168.1.82
ENV hostreal=192.168.1.82
ENV hostdb=192.168.1.82
ENV hosteureka=192.168.1.82
ENTRYPOINT java -jar servicios/productos.jar